-- 内辅配置表（单行配置，id 固定为 1）
CREATE TABLE IF NOT EXISTS `dnf_service`.`ASSIST_CONFIG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONFIG_JSON` LONGTEXT NOT NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
