location ~ ^/assets/* {
    add_header cache-control "max-age=1209600, immutable";
}

location ~ ^/(static|locales)/* {
    add_header cache-control "no-cache";
}

location ~ ^/(|index|signin|login|system|oauth)$ {
        add_header cache-control no-store;
        try_files /index.html =200;
}

location ^~ /biz/ {
        add_header cache-control no-store;
        try_files /index.html =200;
}

set $Cache_Control_val "";
set $Pragma_val "";
set $Expires_val "";

if ($request_uri ~ "\.html$") {
    set $Cache_Control_val "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    set $Pragma_val "no-cache";
    set $Expires_val "0";
}
add_header Cache-Control $Cache_Control_val;
add_header Pragma $Pragma_val;
add_header Expires $Expires_val;