location /app-center {
    proxy_read_timeout 3600s;
    proxy_pass http://unix:/var/run/com.trim.app.center.sock:;
}

location /app-center-static {
    proxy_pass http://unix:/var/run/com.trim.app.center.sock:;
}
