location /v {
    proxy_pass http://unix:/var/run/trim_media.sock:;
    proxy_set_header Host $host; # 保留原始请求的 Host 头部
    proxy_set_header Trim-Host $host;
    proxy_set_header X-Real-IP $remote_addr; # 可选，传递真实 IP
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 可选，传递 X-Forwarded-For 头部
    proxy_max_temp_file_size 0;
}