location /trimcon/redirect {
    if ($http_x_trim_redirect) {
        return 302 $http_x_trim_redirect;
    }
    return 302 https://fnos.net;
}

location /trimcon/cookie {
    add_header Set-Cookie "mode=relay; Path=/; HttpOnly";
    if ($http_x_trim_redirect) {
        return 302 $http_x_trim_redirect;
    }
    return 302 https://fnos.net;
}

location /trimcon {
    # 添加 CORS 头
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' '*';
    add_header 'Access-Control-Allow-Headers' '*';
    add_header 'Access-Control-Request-Private-Network' 'true';

    # 如果请求方法是 OPTIONS，则返回 204
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' '*';
        add_header 'Access-Control-Allow-Headers' '*';
        add_header 'Access-Control-Request-Private-Network' 'true';
        return 204;
    }
    return 200;
}

location /trimfn {
    # 添加 CORS 头
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' '*';
    add_header 'Access-Control-Allow-Headers' '*';
    add_header 'Access-Control-Request-Private-Network' 'true';

    # 如果请求方法是 OPTIONS，则返回 204
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' '*';
        add_header 'Access-Control-Allow-Headers' '*';
        add_header 'Access-Control-Request-Private-Network' 'true';
        return 204;
    }
    proxy_pass http://unix:/var/run/trim-connect.sock; 
}
