# 静态资源配置（优先匹配）
location ^~/iscsi/static/ {
    add_header Cache-Control "no-cache";
    alias /usr/local/apps/@appcenter/trim.iscsi/static/;
}

# 主页面配置
location ^~/iscsi {
    add_header Cache-Control "no-cache";
    alias /usr/local/apps/@appcenter/trim.iscsi/static/;
    index index.html;
    try_files $uri $uri/ /index.html;
}
