[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
MergeTrackersEnabled=true
Session\AddTorrentStopped=false
Session\AddTrackersEnabled=true
Session\AdditionalTrackers=udp://tracker.opentrackr.org:1337/announce\nudp://tracker.openbittorrent.com:80/announce\nudp://exodus.desync.com:6969/announce\nudp://tracker.torrent.eu.org:451/announce\nudp://tracker.moeking.me:6969/announce\nudp://open.stealth.si:80/announce\nudp://tracker.cyberia.is:6969/announce\nudp://tracker3.itzmx.com:6961/announce\nudp://tracker.tiny-vps.com:6969/announce\nudp://tracker-udp.gbitt.info:80/announce\nudp://tracker.leechers-paradise.org:6969/announce\nudp://tracker.pirateparty.gr:6969/announce
Session\AlternativeGlobalDLSpeedLimit=0
Session\AlternativeGlobalUPSpeedLimit=0
Session\DefaultSavePath=/downloads/
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategoryChanged=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\Encryption=1
Session\ExcludedFileNames=
Session\GlobalDLSpeedLimit=0
Session\GlobalMaxRatio=1
Session\GlobalUPSpeedLimit=0
Session\MaxActiveDownloads=20
Session\MaxActiveUploads=20
Session\MaxConnections=3000
Session\MaxConnectionsPerTorrent=400
Session\Port=52345
Session\QueueingSystemEnabled=true
Session\SSL\Port=23595
Session\ShareLimitAction=Stop
Session\SubcategoriesEnabled=true
Session\TempPath=/downloads/incomplete/
Session\TrackerFilteringEnabled=true
Session\UseAlternativeGlobalSpeedLimit=false
Session\UseCategoryPathsInManualMode=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=zh_CN
MailNotification\req_auth=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(nVt3woO47CDFjqlTG36FVg==:zdADtL04fHsjny78M7oOn0RL9v1653ORW9r+Sy1YC+BI4hArEUL1tPDDRknak5+zH22Epb3YmWnvBqecZrzSxQ==)"
WebUI\Port=8086
WebUI\ReverseProxySupportEnabled=false
WebUI\SecureCookie=false
WebUI\ServerDomains=qb.19930901.xyz
WebUI\TrustedReverseProxiesList=qb.19930901.xyz
WebUI\UseUPnP=false
WebUI\Username=admin

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\EnableProcessing=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
Session\FetchDelay=20
Session\RefreshInterval=30
